### ISSUE TITLE
SSL cerficate error

### ISSUE THREAD

**Issue by zhaoturing** [exoframejs/exoframe#198] opened 2019-01-19 02:52 UTC
I got host link from exoframe server successfully.
But when open that link on browser, I got ssl certification error.
Could you help me for that?

**Comment by yamalight** [comment] 2019-01-19 10:07
@zhaoturing have you enabled letsencrypt in server config?
if yes - is your host accessible from the internet? letsencrypt needs host to be publicly available to work correctly

**Comment by zhaoturing** [comment] 2019-01-20 03:07
yes. I have enabled letsencrypt in server config.
and my host is accessible from the internet. 
but when open that host link that get from exoframe on browser firstly , I get ssl certification error.
but if open again, that link is working correctly.
could you tell me what is problem?

**Comment by yamalight** [comment] 2019-01-20 09:03
@zhaoturing does it work correctly now?
if there were some errors in the beginning - that was likely due to Traefik still getting a valid certificate from letsencrypt.

**Comment by zhaoturing** [comment] 2019-01-20 09:07
I think that is error in getting certificate from letsencrypt on traefik.
so How can I find source code that getting certificate from letsencrypt on traefik?
and How could I fix that issue?
I hope you suggest some way for it.
Thank you.

**Comment by yamalight** [comment] 2019-01-20 09:13
@zhaoturing I'd start by inspecting Traefik logs on your server to figure out what exactly the issue is.

**Comment by zhaoturing** [comment] 2019-01-20 09:16
Could you tell me how can I check Traefik log myself? Sorry because others can't access my server for our privacy.

**Comment by yamalight** [comment] 2019-01-20 09:18
@zhaoturing it runs as a docker container, so you'd need to use [`docker logs`](https://docs.docker.com/engine/reference/commandline/logs/) command on your server.

**Comment by yamalight** [comment] 2019-01-20 10:05
@zhaoturing you don't really need any options, you just want to get traefik logs from docker and search for letsencrypt / cert related messages there 🤔

**Comment by zhaoturing** [comment] 2019-01-20 18:35
and can I use other certificate not letsencrypt for solving this?

**Comment by yamalight** [comment] 2019-01-20 19:53
@zhaoturing I never had to deal with letsencrypt and unicode domain names. judging by letsencrypt docs - [it is supported](https://letsencrypt.org/2016/10/21/introducing-idn-support.html), I'm just not sure how to go about it.
Traefik does allow using custom certificates, refer to the [docs here](https://docs.traefik.io/user-guide/examples/#http-redirect-on-https).

Since this is not an exoframe error, I'll close the issue.

**Closed by yamalight** 2019-01-20 19:53 UTC
Labels: type:question

**Comment by zhaoturing** [comment] 2019-01-21 01:34
Thank you

**Comment by zhaoturing** [comment] 2019-01-21 03:19
Hi @yamalight 
I have one question.
can I only change configure file in your source code?
and which link does your server pull traefik from ?

**Comment by yamalight** [comment] 2019-01-21 15:10
@zhaoturing you can provide additional traefik config options using [traefikArgs](https://github.com/exoframejs/exoframe/blob/master/docs/ServerConfiguration.md) option.  
If you need more flexible config, you can start traefik yourself before starting exoframe server and then just tell exoframe-server to use your instance of traefik using [traefikName](https://github.com/exoframejs/exoframe/blob/master/docs/ServerConfiguration.md) config option

**Comment by yamalight** [comment] 2019-01-21 22:11
@zhaoturing exoframe-server doesn't really write any logs (if it's not errors / crashes), but what's available can be read via `docker logs`.

**Comment by zhaoturing** [comment] 2019-01-21 22:13
Thank you
