### ISSUE TITLE
HTTPError: Response code 405 (Method Not Allowed) on login

### ISSUE THREAD

**Issue by VojGin** [exoframejs/exoframe#234] opened 2019-05-14 06:31 UTC
Hello, I encounter the same issue as #190 and #170.

I used exoframe for about a year without a problem.
The issue occured directly after successful:
```
exoframe update
```

When using exoframe login on my work machine, I receive:
```
Logging in to: http://myserverurl:8080
? Username: myusername
? Private key: myprivatekey
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Check your username and password and try again. HTTPError: Response code 405 (Method Not Allowed)
```
I'm certain the path to .ssh/authorized_keys is correct as when i do:
```
docker exec -t exoframe-server /bin/sh -c 'ls -la /root/.ssh'
```

I can see:
```
drwxr-xr-x    2 root     root          4096 May 14 05:58 .
drwx------    1 root     root          4096 May 14 06:03 ..
-rw-r--r--    1 1000     1000          1602 Oct  1  2018 authorized_keys
```

And when I do:
```
docker exec -t exoframe-server /bin/sh -c 'cat /root/.ssh/authorized_keys'
```

I can see (keys are OK):
```
ssh-rsa ***CONFIDENTIAL***
```

I'm using the latest exoframe-server image.
Tried: [restart exoframe container, delete image and rebuild from scratch]
Any idea what could cause this issue? Been pulling my hair for a good 2 hours now.
Thanks for help!

**Comment by yamalight** [comment] 2019-05-14 10:16
Is `***CONFIDENTIAL***` the actual thing you see? Or is there a proper public key?
If there is a public key (btw, no reason hiding it, since it's _public_ key) - make sure your private key is in PEM format (as [documented here](https://github.com/exoframejs/exoframe/blob/master/docs/Basics.md#ssh-key-auth)).

**Comment by VojGin** [comment] 2019-05-14 12:58
Those keys are fine. Just didn't want to publish the whole file including all keys.
Forgot to mention I was running exoframe for about a year and this issue occurred after:
```
exoframe update
```

SSH service is not running in the container or am I wrong?
I'm getting:
```
$ ssh root@172.17.0.4
ssh: connect to host 172.17.0.4 port 22: Connection refused
```

**Comment by yamalight** [comment] 2019-05-14 13:03
There is no SSH service in a container indeed.
What is your actual URL used for Exoframe? Are you using IP address there as well? If yes - that won't work, Exoframe needs domain name

**Comment by VojGin** [comment] 2019-05-14 13:05
Nah, I'm using domain name. As I mentioned previously. I was working with it without a problem daily for the past year.

**Comment by yamalight** [comment] 2019-05-14 13:14
Ah, right, sorry, I somehow totally missed that point. This makes it a whole lot weirder 🤔 
Are you using your own version of traefik or is it the default one from Exoframe?
Also, what does `exoframe version` gives you?

**Comment by VojGin** [comment] 2019-05-14 13:17
Yeah it's really weird.
The default traefik.

```
$ exoframe --version
4.0.1
```
(That's even more weird as it's AFTER update)

**Comment by yamalight** [comment] 2019-05-14 13:20
Ah, sorry, I was asking about server / traefik version from `exoframe update` (I should probably add `exoframe version` that lists all of that 🤔 )

**Comment by yamalight** [comment] 2019-05-14 13:24
I also just noticed that I screwed up bugfix release for the server - could you please update to latest server version (should be 4.1.1) and try again?

**Comment by VojGin** [comment] 2019-05-14 13:42
Running `exoframe update` produces this:
```
{ GotError [HTTPError]: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (/Users/myusername/.nvm/versions/node/v11.14.0/lib/node_modules/exoframe/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  name: 'HTTPError',
  host: 'my.server.domain:8080',
  hostname: 'my.server.domain',
  method: 'GET',
  path: '/version',
  socketPath: undefined,
  protocol: 'http:',
  url: 'http://my.server.domain:8080/version',
  gotOptions:
   { path: '/version',
     protocol: 'http:',
     slashes: true,
     auth: null,
     host: 'my.server.domain:8080',
     port: '8080',
     hostname: 'my.server.domain',
     hash: null,
     search: null,
     query: null,
     pathname: '/version',
     href: 'http://my.server.domain:8080/version',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set] },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        authorization:
         'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnZWRJbiI6dHJ1ZSwidXNlciI6eyJ1c2VybmFtZSI6InZvamdpbiJ9LCJpYXQiOjE1NDY4NjkyMjd9.Kn1MscdbH4D9fPhKo7BKM-iRj_MINp_3cAtQdEKAo9Y',
        accept: 'application/json',
        'accept-encoding': 'gzip, deflate',
        'content-type': 'application/json',
        'content-length': 2 },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: true,
     cache: false,
     useElectronNet: false,
     body: '{}',
     method: 'GET' },
  statusCode: 500,
  statusMessage: 'Internal Server Error',
  headers:
   { 'access-control-allow-origin': '*',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '12',
     date: 'Tue, 14 May 2019 13:37:26 GMT',
     connection: 'close' },
  body: { error: {} } }
```
Where `my.server.domain` is where my actual domain name is, just changed it for the purpose of this ticket.

**Comment by yamalight** [comment] 2019-05-14 14:20
Alright, that's definitely a bug. I was able to reproduce that. Will try to figure out what's up with this in the next days - PRs are welcome if you can figure it out faster though :)

W.r.t. original issue with login - I'm guessing it probably has something to do with a Traefik update, although I wasn't able to reproduce this on my servers 🤔 
Could you try re-creating exoframe server container to see if that solves it?

**Comment by yamalight** [comment] 2019-05-14 14:38
Alright, I fixed the `update` problem (was due to Traefik label changes), will push an update out in a few mins.

**Comment by yamalight** [comment] 2019-05-14 14:57
And released. You'll need to manually update it though since that version bug totally breaks auto-update procedure :(

**Comment by VojGin** [comment] 2019-05-14 15:17
Built from source:
```
$ exoframe update
✔ You are up to date!

Exoframe Server:
  current: 4.1.2
  latest: 4.1.2

Traefik:
  current: v1.7.11
  latest: v1.7.11
```

Unfortunately the problem with login persists.
```
$ exoframe login
Logging in to: http://my.server.domain:8080
? Username: vojgin
? Private key: id_rsa
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Check your username and password and try again. HTTPError: Response code 405 (Method Not Allowed)
```

```
$ docker exec -t exoframe-server /bin/sh -c 'cat /root/.ssh/authorized_keys'
ssh-rsa AAAAB3NzaC1yc2EAAAA.......(the list goes on, and on)
```

**Comment by yamalight** [comment] 2019-05-14 15:58
Could you please [validate](https://serverfault.com/questions/426394/how-to-check-if-an-rsa-public-private-key-pair-match/426429#426429) that your pubkey and private key you use do indeed match? Just for the sake of sanity 🤔

**Comment by VojGin** [comment] 2019-05-14 16:37
Can't manage to get SSH running in the container.
Nevertheless are those the same pub-private pairs that are used to SSH onto the server from my computer. I'm certain they are correct, because otherwise I could not SSH onto the server in the first place.

**Comment by yamalight** [comment] 2019-05-14 17:13
Ah, that's what I was asking initially - so it does work when SSH-ing into the server 🤔 
Could you try generating a new key pair and using it? Does that work or does it still fail?

**Comment by VojGin** [comment] 2019-05-14 19:11
Oh sorry, I didn't realize I use the same pairs for this purpose...

Fails even after generating new pair or flushing the authorized_keys and filling it with the only new generated public key.

I'm running the container now from:
```
$ node /exoframe-server/index.js
```
as Entrypoint

Is there anything I could change in the source code so I could debug the reading process of the authorized_keys file and so on? Don't know where to put some clever console.log at the moment.

**Comment by yamalight** [comment] 2019-05-14 19:26
This is the spot that fails for you right now:
https://github.com/exoframejs/exoframe-server/blob/master/src/auth/index.js#L78-L87

So, the error should originate somewhere there 🤔

**Comment by VojGin** [comment] 2019-05-14 19:46
Hooray!
```
Logging in to: http://my.server.domain:8080
? Username: vojgin
? Private key: id_rsa
? Private key passpharse (leave blank if not set): [hidden]
Successfully logged in!
```

Added this before line 89
```
console.log(`Could not read public keys file! ${e.toString()}`)
```

And it resulted into:
```
Could not read public keys file! Error: ENOENT: no such file or directory, open '/home/vojgin/.ssh/authorized_keys'
```

So I looked into `server.config.yml`
And found this:
```
# path to folder with authorized_keys, default "~/.ssh"
publicKeysPath: '/home/vojgin/.ssh/'
```

Before you start thinking about me I am a total dumbass 🤦🏼‍♂️, let me make clear there was no edit by me to the file for last 7 months and exoframe-server was working just fine. (Just checked that on an old snapshot image backup of the server debian)

So I have a few ideas what could happen:
- ~/.ssh got somehow evaluated into that path during the update
- this config was ignored in all previous versions?
- my server did some douchebag rollback/fileswap without any reason
- aliens 👽

Can you please confirm that options 1 or 2 are not possible? 🤷🏼‍♂️

**Comment by yamalight** [comment] 2019-05-14 19:51
1. Exoframe definitely doesn't apply any changes to config during update
2. If you mounted that folder - it shouldn't have been 🤔 
Theoretically it also shouldn't touch the config file at all if it already exists, so changes are unlikely.I'd say 3-4 have higher probabilities 😅 
Have you ran exoframe-server outside of docker on that server? Maybe directly using node.js? That might've caused it to edit the config. But once again - if file was already there, it shouldn't have been modified 🤔 

I also guess we need to send better errors to client 🤔

**Comment by yamalight** [comment] 2019-05-14 19:51
I'll close this, but feel free to open new issues if you have more problems :)

**Closed by yamalight** 2019-05-14 19:51 UTC
Labels: component:server, status:PR welcome, status:needs research, type:bug

**Comment by VojGin** [comment] 2019-05-14 19:55
Thanks for the help Tim! Keep the great work on exoframe. 🥇
