### ISSUE TITLE
node-scss crashing on deployment time

### ISSUE THREAD

**Issue by felixfong227** [exoframejs/exoframe#128] opened 2018-03-27 17:04 UTC
Application: React application(ejected) with SCSS feature
For some reason, when trying to install node-scss during deployment time it, it just keep failing.
But everything works out very well in the Docker Cloud and local development environment.

OS: OSX 10.11.6
Node: 9.3.0
Exoframe: 2.1.1

Dockerfile
```dockerfile
FROM node

WORKDIR /app

COPY package.json .

RUN npm install

# RUN npm install yarn -g

# RUN yarn install --no-lockfile

COPY . .

RUN npm run build

# RUN yarn run build

# RUN yarn global add serve

RUN npm install serve -g

RUN serve -s build

EXPOSE 5000
```

Logs during deployment
![image](https://user-images.githubusercontent.com/13918481/37983022-beefe56c-3224-11e8-8a8b-3c2485e32ec9.png)

**Comment by yamalight** [comment] 2018-03-27 17:52
Could you please provide a minimal repo that reproduces this?

**Comment by yamalight** [comment] 2018-03-27 17:55
Also, could you please try to run it with `-vvv` flag (very verbose mode) and share the log here?

**Comment by felixfong227** [comment] 2018-03-28 06:28
Logs under VVV flag
![image](https://user-images.githubusercontent.com/13918481/38012375-dbc9300c-3293-11e8-9cc4-87777c97163f.png)

Text version of it
```
Deploying current project to endpoint: http://exoframe.hoovessound.ml

No .exoframeignore file found, using default ignores

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
[info] Deploying Dockerfile project..
[verbose] Building image with tag: exo-felixfong-227-hs-material-client:latest
[verbose] Step 1/9 : FROM node

[verbose] {"status":"Pulling from library/node","id":"latest"}
[verbose] {"status":"Digest: sha256:0b02160d1dc9d2afcdd17ab2c106884b656604f763fd905cbde51c31ecc7d795"}
[verbose] {"status":"Status: Image is up to date for node:latest"}
[verbose]  ---> 4885ab8871c2

[verbose] Step 2/9 : WORKDIR /app

[verbose]  ---> Using cache

[verbose]  ---> ef4bfa1051d5

[verbose] Step 3/9 : COPY package.json .

[verbose]  ---> Using cache

[verbose]  ---> 1a84e6b1851e

[verbose] Step 4/9 : RUN npm install

[verbose]  ---> Running in 30f406663328

Error deploying project: Error: Something went wrong!
Build log:

No log available

Original error: { Error: Something went wrong!
    at Object.exports.handler (/usr/local/share/.config/yarn/global/node_modules/exoframe/src/commands/deploy.js:191:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) response: {} }
Original response: {}
```

Repo: https://github.com/hoovessound/hs-material-client/tree/exoframe-cd

**Comment by yamalight** [comment] 2018-03-28 09:42
OK, got it. Will have a look at the repo once I have time

**Comment by yamalight** [comment] 2018-07-10 12:11
I've just changed the behaviour in `exoframe-server:develop` branch / docker image (not yet released in stable). It should not longer fail due to simple issues in the log.
I'm going to close this ticket, feel free to open a new one if that still happens with new version.

**Closed by yamalight** 2018-07-10 12:11 UTC
Labels: status:needs triage, type:bug

**Comment by maxime1992** [comment] 2019-01-25 09:40
Just ran into this issue and upgrading with target `all` (exoframe upgrade -t all) fixed it :tada: 

Thanks @yamalight :raised_hands:
